on:
  issues:
    types: [opened]
jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            This plugin is currently unmaintained and looking for adoption: #7. As @foosel has her hands full with
            maintaining OctoPrint itself, issues here will not be processed. Sorry.
